version: "3.7"

# This file is used to test the docker image. To host pyShelf yourself for 
# production, please use the official pyShelf image on 
# https://hub.docker.com/r/pyshelf/pyshelf

# For development, use the following command in the root folder:
# `docker-compose -f .\docker\development.docker-compose.yml up --build`

services:
    db:
        image: "postgres"
        environment:
            - "POSTGRES_PASSWORD=pyshelf"
            - "POSTGRES_USER=pyshelf"
            - "POSTGRES_DB=pyshelf"
        volumes:
            - "db_data:/var/lib/postgresql/data/"

    pyshelf:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile
        ports: 
            - "8080:8000"
        volumes:
            - "${LOCAL_BOOK_DIR}:/books"
        depends_on:
            - db

volumes:
    db_data: